name: datalakeAgent_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - matplotlib
  - tqdm
  - colorama
  - pydantic
  - pip
  - pip:
      - tiktoken
      - openai
